<?php

/*
* @name CB_notice_board 1.01
* Created By Guarneri Iacopo
* http://www.iacopo-guarneri.me/
* @license http://www.gnu.org/copyleft/gpl.html GNU/GPL
*/

	class notice_board_language {
		public $da = 'by';
		public $il = 'on';
		public $alle = 'at';
		public $invia = 'Post';
		public $segnala='Report!';
		public $commenta = 'Comment';
		public $mostra = 'Show';
		public $oggetto_segnalazione='Report of abuse on the noticeboard of [site_name]';
		public $txt_segnalazione='A user has reported that the post with id=[id] on the noticeboard of [site_name] is inappropriate in some way and will be investigated by the administrators of the site';
		public $oggetto_evento='A new message has been posted on the Noticeboard of [site_name]';
		public $txt_evento='A user has posted a message to the noticeboard of [site_name]';
		public $oggetto_messaggio='There is a new message on the noticeboard of [site_name]';
		public $txt_messaggio='[from_first_name] [from_last_name] ([from_user]) wrote on your noticeboard.
		This message is automatically generated by [site_name]
		Click on [site_link] to view your noticeboard.
		
		If you no longer wish to receive such notifications please click the following link:
		[remove_mail]';
		
		public $oggetto_segnalato='You have been reported for an inappropriate post to a noticeboard on [site_name]';
		public $txt_segnalato='You have been reported for an inappropriate comment on the noticeboard of the Site [site_name].
		
		Comment:';
		public $antiflood='Before you post again you must wait';
		public $pagina_precedente='previous page';
		public $pagina_successiva='next page';
		public $inserisci_url='Enter the web address';
		public $inserisci_urlname='Enter the name of the web address';
		public $inserisci_urlimg='enter the web location of your image';
		public $inserisci_urlyoutube='Enter the youtube id (e.g.: KXdUNp_9oHs)';
		public $title_link='Insert Hyperlink';
		public $title_img='Insert images';
		public $title_youtube='Add video links from youtube';
		public $segnalazione_inviata='An email has been sent to the administrators of this site registering your concern. The administrators will check whether the item you have reported violates the site regulations, discuss with the relevant parties and get back to you as soon as possible.';
		public $cancella_error='You cannot delete the posts of others';
		public $segnala_alert='You sure you want to report this post to administrators?';
		
		public $lestensione_txt = "extension ";
		public $non_consentita_txt = " is not 'allowed";
		public $la_cartella_txt = "The folder ";
		public $non_esiste_txt = " does not exist";
		public $errore_upload_txt = "Error during upload ";
		public $grandezza_minore_txt = "The file size should be smaller than ";
		public $grandezza_maggiore_txt = "The file size must be greater than 0 bytes";
		public $incolla_codice_immagine="Close this window to insert the image";
		
		public $condividi_but = "Share";
		public $condividi = "shared by a post";
	}
?>
